{{- if and .Values.operator .Values.operator.enable -}}
{{- if .Values.operator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kaspr.operator.serviceAccountName" . }}
  namespace: {{ include "kaspr.operator.namespace" . }}
  labels:
    {{- include "kaspr.operator.labels" . | nindent 4 }}
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.operator.serviceAccount.automount }}
{{- end }}
{{- end }}