{{- if and .Values.operator .Values.operator.enable .Values.operator.rbac.create }}
{{- $root := . -}}
{{- $opns := include "kaspr.operator.namespace" . -}}
{{- range append .Values.operator.watchNamespaces $opns }}
---
apiVersion: rbac.authorization.k8s.io/v1
{{- if $root.Values.operator.watchAnyNamespace }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
metadata:
  {{- if $root.Values.operator.watchAnyNamespace }}
  name: kaspr-operator-namespaced
  {{- else }}
  name: kaspr-operator
  {{- end }}
  namespace: {{ . }}
  labels:
    component: role-binding
    {{- include "kaspr.operator.labels" $root | nindent 4 }}   
subjects:
  - kind: ServiceAccount
    name: {{ include "kaspr.operator.serviceAccountName" $root }}
    namespace: {{ include "kaspr.operator.namespace" $root }}
roleRef:
  kind: ClusterRole
  name: kaspr-operator-namespaced
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}