{{- if and .Values.operator .Values.operator.enable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaspr.operator.fullname" . }}
  namespace: {{ include "kaspr.operator.namespace" . }}
  labels:
    {{- include "kaspr.operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.operator.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.operator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kaspr.operator.selectorLabels" . | nindent 4 }}
{{- end }}